language: node_js
node_js:
- '8'
env:
  global:
    secure: dO//bpCT7S21p6WT6QcBBTdBlSsLraBHwkUFGnKvOCjH5ZpIcUY4CijfvptNUGck7q+FmI8InX8LDzSYUUvtVOkVuRWj0PIaR/oOy7lsQ59DJyC7oxmgDBTxWlpakYasY6q4riGaLZvwCZymHhBuRGoEZKp5Vt6xVUqHd7ajEadFT6tjenMRBZUt2QIhnbghIKmTp1sGhxxnRZiygask1SyenZv7cWypdxAEyCXAfpSfHCrQpquv8gSSl7k6Oc2KKZxRI3EQ5WZwaEjEUGp8bJ11OJinrxPOjN+jeBMIxL6mpMS4yp3memByKj4pgR52741Mwnxc7dtGOhCQPtokydg0hhhRKGD+pKloN0y9C6atqlJbAj5SEkKbVeb1dMoxyNN/3qnZQQB/PLZJ+u9YEVSSNAJzAdCN1WeK4t0zWSt6HkgJeJyq5ZvMMyQZnLY6JTHPUl3AZpwxDBKGRvdzafNoX692RlMldgMOYIezcO0eeOymPJVSOPZ/P/DYV+UN7UPGeU022IsRZcx8pwAfnXl67HEi7ntjX5Q/SWMiFpQYLCM4ej6K47/o+sf7KNn6JsoKoswxVOumqizEfRs7zhEXTY0S3JpyU7LeEJoT2fIy9CNQ/vKlgFEzRaWmajD3PslE9bPiIDtvqH6R9F2YyJy1Pi3v3gTu3McLHNuOja0=
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: kittyhats-manifest
  skip_cleanup: true
  local_dir: build
  region: us-west-2
  cache_control: max-age=21600
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID
  --paths "/*"
